-- MySQL Script generated by MySQL Workbench
-- 06/26/18 17:22:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_md
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_md
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_md` DEFAULT CHARACTER SET utf8 ;
USE `bd_md` ;

-- -----------------------------------------------------
-- Table `bd_md`.`caixasugestao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_md`.`caixasugestao` (
  `idcaixasugestao` INT(11) NOT NULL AUTO_INCREMENT,
  `comentario` TEXT NOT NULL,
  `situacao` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idcaixasugestao`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_md`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_md`.`curso` (
  `idcurso` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_md`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_md`.`perfil` (
  `idperfil` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_md`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_md`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `perfil_idperfil` INT(11) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  INDEX `fk_coordenador_perfil1_idx` (`perfil_idperfil` ASC),
  CONSTRAINT `fk_coordenador_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `bd_md`.`perfil` (`idperfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_md`.`slide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_md`.`slide` (
  `idslide` INT(11) NOT NULL AUTO_INCREMENT,
  `slide` VARCHAR(255) NOT NULL,
  `usuario_idusuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idslide`),
  INDEX `fk_slide_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_slide_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bd_md`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_md`.`informacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_md`.`informacao` (
  `idinformacao` INT(11) NOT NULL AUTO_INCREMENT,
  `informacao` TEXT NOT NULL,
  `tipo` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NULL DEFAULT NULL,
  `curso_idcurso` INT(11) NULL DEFAULT NULL,
  `slide_idslide` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idinformacao`),
  INDEX `fk_informacao_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_informacao_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_informacao_slide1_idx` (`slide_idslide` ASC),
  CONSTRAINT `fk_informacao_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `bd_md`.`curso` (`idcurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_informacao_slide1`
    FOREIGN KEY (`slide_idslide`)
    REFERENCES `bd_md`.`slide` (`idslide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informacao_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bd_md`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_md`.`respostacaixasugestao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_md`.`respostacaixasugestao` (
  `usuario_idusuario` INT(11) NOT NULL,
  `resposta` TEXT NULL DEFAULT NULL,
  `idresposta` INT(11) NOT NULL AUTO_INCREMENT,
  `caixasugestao_idcaixasugestao` INT(11) NOT NULL,
  PRIMARY KEY (`idresposta`),
  INDEX `fk_ouvidoria_has_usuario_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_respostacaixasugestao_caixasugestao1_idx` (`caixasugestao_idcaixasugestao` ASC),
  CONSTRAINT `fk_ouvidoria_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bd_md`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_respostacaixasugestao_caixasugestao1`
    FOREIGN KEY (`caixasugestao_idcaixasugestao`)
    REFERENCES `bd_md`.`caixasugestao` (`idcaixasugestao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_md`.`usuario_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_md`.`usuario_curso` (
  `usuario_idusuario` INT(11) NOT NULL,
  `curso_idcurso` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `curso_idcurso`),
  INDEX `fk_usuario_has_curso_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_usuario_has_curso_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `bd_md`.`curso` (`idcurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_has_curso_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bd_md`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
